apiVersion: v1
kind: ConfigMap
metadata:
  name: aimqwen38llama-env
  namespace: {{ .Release.Namespace }}
  labels:
    app: aimqwen38llama
    app.kubernetes.io/managed-by: Helm
data:
  CTX_SIZE: "125000"
  TARGET_FILE: "RVN-Q4_K_M-mtp.gguf"
  TARGET_URL: "https://huggingface.co/0bserverx/Qwen3.8-27B-Heretic-Abliterated-Uncensored-GGUF/resolve/main/RVN-Q4_K_M-mtp.gguf"
  MMPROJ_FILE: "mmproj-0bserverx-Q8_0.gguf"
  MMPROJ_URL: "https://huggingface.co/0bserverx/Qwen3.8-27B-Heretic-Abliterated-Uncensored-GGUF/resolve/main/mmproj-Qwen3.8-27B-Q8_0.gguf"
  KV_TYPE: "{{ .Values.env.KV_TYPE }}"
  MODEL_ALIAS: "{{ .Values.env.MODEL_ALIAS }}"
  THREADS: "{{ .Values.env.THREADS }}"
  PARALLEL: "{{ .Values.env.PARALLEL }}"
  CACHE_REUSE: "{{ .Values.env.CACHE_REUSE }}"
  SPEC_TYPE: "draft-dflash"
  DRAFT_MAX: "7"
  DRAFT_MODEL_FILE: "Qwen3.8-27B-DFlash2-Q4_K_M.gguf"
  DRAFT_MODEL_URL: "https://huggingface.co/incoai/Qwen3.8-27B-DFlash2-GGUF/resolve/main/Qwen3.8-27B-DFlash2-Q4_K_M.gguf"
